#!/usr/bin/env python3
"""Auto-generate per-pixel material overrides for stock ET textures (no map recompile).

For each stock texture, extracts the *retail* diffuse from pak0 and derives:
  - a tangent-space normal map (local-contrast height -> normal, height in alpha)
  - a specular map (brightness-following)
and emits a renderer2 shader that overrides the stock texture with
diffuseMap/bumpMap/specularMap. Dropping the result in etmain makes every map using
those textures pick up per-pixel lighting under `cl_renderer gl2` -- the .bsp is never
touched. This is the same generator used for the oasis_rm conversion and the HD demo.

Output (under <outdir>):  textures/rm_hd/<name>_n.tga, _s.tga  +  scripts/rm_hd.shader

Usage:  python make_hd_materials.py [outdir] [--pak0 PATH]
        (edit TEXES below for the texture set; default = oasis's prominent textures)
"""
import io
import os
import sys
import zipfile

import numpy as np
from PIL import Image, ImageFilter

PAK0_DEFAULT = r"C:\repo\enemy-territory-RM\etmain\pak0.pk3"

# Oasis's most-referenced wall/floor/trim textures (implicit/overridable).
TEXES = [
    "egypt_walls_sd/stucco08d", "egypt_walls_sd/stucco08a", "egypt_walls_sd/stucco08e",
    "egypt_walls_sd/stucco07c", "egypt_walls_sd/stucco07a", "egypt_walls_sd/stucco07b",
    "egypt_walls_sd/stucco07d", "egypt_walls_sd/stucco07f", "egypt_walls_sd/stucco07_trim03",
    "egypt_walls_sd/stucco09e", "egypt_walls_sd/stucco09c", "egypt_walls_sd/stucco09f",
    "egypt_walls_sd/bigblock02", "egypt_walls_sd/roughedge01", "egypt_walls_sd/roughbrick01",
    "egypt_floor_sd/siwa_rubble_1", "egypt_trim_sd/trim_c03c",
]

NORMAL_STRENGTH = 7.0   # height->normal gain (higher = more pronounced relief)


def write_tga(path, rgba):
    h, w, _ = rgba.shape
    hdr = bytearray(18); hdr[2] = 2
    hdr[12] = w & 255; hdr[13] = w >> 8; hdr[14] = h & 255; hdr[15] = h >> 8
    hdr[16] = 32; hdr[17] = 8
    with open(path, "wb") as f:
        f.write(bytes(hdr)); f.write(np.ascontiguousarray(rgba[::-1, :, [2, 1, 0, 3]]).tobytes())


def load_diffuse(z, base):
    for ext in (".tga", ".jpg", ".jpeg"):
        try:
            return Image.open(io.BytesIO(z.read("textures/" + base + ext))).convert("RGB")
        except KeyError:
            continue
    raise FileNotFoundError(base)


def normal_from_height(h, strength):
    gy, gx = np.gradient(h.astype(np.float64))
    nx, ny, nz = -gx * strength, -gy * strength, np.ones_like(h, np.float64)
    n = np.sqrt(nx * nx + ny * ny + nz * nz)
    out = np.empty(h.shape + (4,), np.uint8)
    out[..., 0] = np.clip((nx / n * .5 + .5) * 255, 0, 255)
    out[..., 1] = np.clip((ny / n * .5 + .5) * 255, 0, 255)
    out[..., 2] = np.clip((nz / n * .5 + .5) * 255, 0, 255)
    out[..., 3] = np.clip(h * 255, 0, 255)   # parallax height in alpha
    return out


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 and not sys.argv[1].startswith("--") else "."
    pak0 = PAK0_DEFAULT
    if "--pak0" in sys.argv:
        pak0 = sys.argv[sys.argv.index("--pak0") + 1]
    texdir = os.path.join(outdir, "textures", "rm_hd")
    scrdir = os.path.join(outdir, "scripts")
    os.makedirs(texdir, exist_ok=True); os.makedirs(scrdir, exist_ok=True)
    shader = ["// rm_hd: per-pixel material override for stock ET textures (gl2 only).",
              "// Generated by tools/oasis_rm/make_hd_materials.py -- no map recompile.\n"]
    with zipfile.ZipFile(pak0) as z:
        for t in TEXES:
            base = t.split("/")[-1]
            try:
                img = load_diffuse(z, t)
            except FileNotFoundError:
                print("skip (no base image):", t); continue
            lum = np.asarray(img.convert("L"), np.float64) / 255.0
            blur = np.asarray(Image.fromarray((lum * 255).astype(np.uint8))
                              .filter(ImageFilter.GaussianBlur(max(lum.shape) / 24.0)), np.float64) / 255.0
            height = np.clip(0.5 + (lum - blur) * 2.2, 0, 1)
            write_tga(os.path.join(texdir, base + "_n.tga"), normal_from_height(height, NORMAL_STRENGTH))
            sv = (np.clip(0.20 + lum * 0.55, 0, 0.85) * 255).astype(np.uint8)
            write_tga(os.path.join(texdir, base + "_s.tga"),
                      np.stack([sv, sv, sv, np.full_like(sv, 255)], -1))
            shader += ["textures/%s" % t, "{",
                       "\tqer_editorimage textures/%s.tga" % t,
                       "\tdiffuseMap textures/%s" % t,
                       "\tbumpMap textures/rm_hd/%s_n.tga" % base,
                       "\tspecularMap textures/rm_hd/%s_s.tga" % base, "}", ""]
            print("hd:", t, img.size)
    open(os.path.join(scrdir, "rm_hd.shader"), "w", newline="\n").write("\n".join(shader))
    print("-> materials + scripts/rm_hd.shader in", outdir)


if __name__ == "__main__":
    main()
