// ET-RM R2-6 showcase materials (project-original, generated by make_showcase_textures.py).
// renderer2 (gl2) per-pixel material keywords per src/renderer2/etl/tr_shader.c:
//   diffuseMap/bumpMap/specularMap (4442-4463) + 'parallax' (4051).
// gl1 (original renderer) ignores these keywords and falls back to the editor image
// lightmapped; the showcase is a gl2 feature demo.
textures/rm_showcase/rivet
{
	qer_editorimage textures/rm_showcase/rivet_d.tga
	diffuseMap textures/rm_showcase/rivet_d.tga
	bumpMap textures/rm_showcase/rivet_n.tga
	specularMap textures/rm_showcase/rivet_s.tga
	parallax
}
textures/rm_showcase/block
{
	qer_editorimage textures/rm_showcase/block_d.tga
	diffuseMap textures/rm_showcase/block_d.tga
	bumpMap textures/rm_showcase/block_n.tga
	specularMap textures/rm_showcase/block_s.tga
	parallax
}
textures/rm_showcase/stud
{
	qer_editorimage textures/rm_showcase/stud_d.tga
	diffuseMap textures/rm_showcase/stud_d.tga
	bumpMap textures/rm_showcase/stud_n.tga
	specularMap textures/rm_showcase/stud_s.tga
	parallax
}
