#!/usr/bin/env python3
"""R2-5 Task 4 positive-proof test material generator (reproducible).

Generates LOOSE homepath files (never shipped; build dir is gitignored):
  <homepath>/scripts/rm_test.shader            - overrides ONE stock wall texture
  <homepath>/textures/rm_test/rm_test_d.tga    - diffuse (extracted from retail pak0,
                                                 or a magenta locator grid with --marker)
  <homepath>/textures/rm_test/rm_test_n.tga    - tangent-space normal map: diagonal
                                                 grooves + bump grid, height in alpha
                                                 (renderer2 reliefMapping reads .a)
  <homepath>/textures/rm_test/rm_test_s.tga    - non-flat specular map (checker)

The target texture is textures/egypt_walls_sd/stucco03_dark: the wall at screen
center of the T3 panzerfaust dlight scene (goldrush allied-side courtyard,
setviewpos -2184 -972 30 45; identified by BSP view-ray analysis), and it has
NO explicit shader definition in pak0 scripts (implicit lightmapped texture), so
this loose override is the only definition and unambiguously wins.

Material syntax per vendored src/renderer2/etl/tr_shader.c: top-level keywords
diffuseMap/bumpMap/specularMap (tr_shader.c:4442-4463) and 'parallax'
(tr_shader.c:4051) which sets shader.parallax, required by the
use_parallaxMapping gates in tr_shade.c.

Usage:
  python make_test_material.py            # install with retail diffuse
  python make_test_material.py --marker   # install with magenta locator diffuse
  python make_test_material.py --remove   # remove all generated files (clean homepath)
"""

import argparse
import os
import sys
import zipfile

import numpy as np

HOMEPATH_DEFAULT = r"C:\repo\et-rm\build\bin\etmain"
PAK0_DEFAULT = r"C:\repo\enemy-territory-RM\etmain\pak0.pk3"
TARGET = "textures/egypt_walls_sd/stucco03_dark"  # implicit (no shader def in pak0 scripts)

SHADER_TEXT = """// R2-5 T4 positive-proof test material (generated by make_test_material.py).
// Verification-only loose homepath override - NEVER shipped.
{target}
{{
\tqer_editorimage {target}.tga
\tdiffuseMap textures/rm_test/rm_test_d.tga
\tbumpMap textures/rm_test/rm_test_n.tga
\tspecularMap textures/rm_test/rm_test_s.tga
\tparallax
}}
"""

GENERATED = (
    "scripts/rm_test.shader",
    "textures/rm_test/rm_test_d.tga",
    "textures/rm_test/rm_test_n.tga",
    "textures/rm_test/rm_test_s.tga",
)


def write_tga(path, rgba):
    """Write an uncompressed 32-bit TGA (origin bottom-left) from HxWx4 uint8."""
    h, w, _ = rgba.shape
    header = bytearray(18)
    header[2] = 2  # uncompressed truecolor
    header[12] = w & 0xFF
    header[13] = (w >> 8) & 0xFF
    header[14] = h & 0xFF
    header[15] = (h >> 8) & 0xFF
    header[16] = 32  # bpp
    header[17] = 8   # 8 alpha bits, bottom-left origin
    bgra = rgba[::-1, :, [2, 1, 0, 3]]  # flip rows, RGB->BGR
    with open(path, "wb") as f:
        f.write(bytes(header))
        f.write(np.ascontiguousarray(bgra).tobytes())


def make_height(size=512):
    """Obvious pattern: deep diagonal grooves + a coarse bump grid. Range 0..1."""
    y, x = np.mgrid[0:size, 0:size].astype(np.float64)
    # diagonal grooves: 8 periods across the image
    grooves = 0.5 + 0.5 * np.sin((x + y) * (2 * np.pi * 8 / size))
    grooves = grooves ** 3  # sharpen into grooves
    # coarse bump grid: 4x4 round bumps
    cell = size // 4
    cx = (x % cell) - cell / 2
    cy = (y % cell) - cell / 2
    r = np.sqrt(cx * cx + cy * cy) / (cell / 2)
    bumps = np.clip(1.0 - r, 0.0, 1.0) ** 2
    return np.clip(0.65 * grooves + 0.35 * bumps, 0.0, 1.0)


def make_normal_map(size=512, strength=6.0):
    """Tangent-space normal map from the height field; height stored in alpha."""
    hgt = make_height(size)
    gy, gx = np.gradient(hgt)
    nx = -gx * strength
    ny = -gy * strength
    nz = np.ones_like(hgt)
    norm = np.sqrt(nx * nx + ny * ny + nz * nz)
    rgba = np.empty((size, size, 4), dtype=np.uint8)
    rgba[..., 0] = np.clip((nx / norm * 0.5 + 0.5) * 255, 0, 255).astype(np.uint8)
    rgba[..., 1] = np.clip((ny / norm * 0.5 + 0.5) * 255, 0, 255).astype(np.uint8)
    rgba[..., 2] = np.clip((nz / norm * 0.5 + 0.5) * 255, 0, 255).astype(np.uint8)
    rgba[..., 3] = np.clip(hgt * 255, 0, 255).astype(np.uint8)  # parallax height
    return rgba


def make_specular_map(size=256):
    """Non-flat specular: 8x8 checker, bright vs dark."""
    y, x = np.mgrid[0:size, 0:size]
    checker = (((x // (size // 8)) + (y // (size // 8))) % 2).astype(np.uint8)
    v = np.where(checker == 1, 230, 25).astype(np.uint8)
    rgba = np.stack([v, v, v, np.full_like(v, 255)], axis=-1)
    return rgba


def make_marker_diffuse(size=256):
    """Magenta locator with black grid - used only to find override coverage."""
    rgba = np.zeros((size, size, 4), dtype=np.uint8)
    rgba[..., 0] = 255
    rgba[..., 2] = 255
    rgba[..., 3] = 255
    step = size // 8
    rgba[::step, :, 0:3] = 0
    rgba[:, ::step, 0:3] = 0
    return rgba


def extract_retail_diffuse(pak0, target):
    """Pull the retail TGA out of pak0 and return as HxWx4 uint8 (via PIL)."""
    from PIL import Image
    import io
    with zipfile.ZipFile(pak0) as z:
        data = z.read(target + ".tga")
    img = Image.open(io.BytesIO(data)).convert("RGBA")
    return np.array(img)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--homepath", default=HOMEPATH_DEFAULT)
    ap.add_argument("--pak0", default=PAK0_DEFAULT)
    ap.add_argument("--marker", action="store_true",
                    help="use a magenta locator grid as diffuse instead of the retail image")
    ap.add_argument("--remove", action="store_true",
                    help="remove all generated files from the homepath")
    args = ap.parse_args()

    if args.remove:
        for rel in GENERATED:
            p = os.path.join(args.homepath, rel.replace("/", os.sep))
            if os.path.exists(p):
                os.remove(p)
                print("removed", p)
        d = os.path.join(args.homepath, "textures", "rm_test")
        if os.path.isdir(d) and not os.listdir(d):
            os.rmdir(d)
            print("removed", d)
        return 0

    os.makedirs(os.path.join(args.homepath, "scripts"), exist_ok=True)
    os.makedirs(os.path.join(args.homepath, "textures", "rm_test"), exist_ok=True)

    if args.marker:
        diffuse = make_marker_diffuse()
    else:
        diffuse = extract_retail_diffuse(args.pak0, TARGET)

    write_tga(os.path.join(args.homepath, "textures", "rm_test", "rm_test_d.tga"), diffuse)
    write_tga(os.path.join(args.homepath, "textures", "rm_test", "rm_test_n.tga"), make_normal_map())
    write_tga(os.path.join(args.homepath, "textures", "rm_test", "rm_test_s.tga"), make_specular_map())

    shader_path = os.path.join(args.homepath, "scripts", "rm_test.shader")
    with open(shader_path, "w", newline="\n") as f:
        f.write(SHADER_TEXT.format(target=TARGET))

    print("installed test material overriding", TARGET,
          "(marker diffuse)" if args.marker else "(retail diffuse)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
